# Generated by Django 3.0.6 on 2020-09-29 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0002_hire_manager_profile_pic'),
        ('job', '0007_auto_20200827_1540'),
        ('freelancer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_time', models.DateTimeField(auto_now_add=True)),
                ('message_text', models.TextField(null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Purposal_status_catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Purposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purposal_time', models.DateTimeField(auto_now_add=True)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.TextField()),
                ('days', models.IntegerField(null=True)),
                ('title', models.CharField(max_length=255, null=True)),
                ('client_grade', models.DecimalField(decimal_places=1, max_digits=1, null=True)),
                ('client_comment', models.TextField(null=True)),
                ('freelancer_grade', models.DecimalField(decimal_places=1, max_digits=1, null=True)),
                ('freelancer_comment', models.TextField(null=True)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freelancer.Freelancer')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.Job')),
                ('payment_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='freelancer.Payment_type')),
                ('purposal_status_catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purposal_contract.Purposal_status_catalog')),
            ],
        ),
        migrations.CreateModel(
            name='Parent_message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_message', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='purposal_contract.Message')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='purposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purposal_contract.Purposal'),
        ),
        migrations.AddField(
            model_name='message',
            name='purposal_status_catalog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='purposal_contract.Purposal_status_catalog'),
        ),
        migrations.CreateModel(
            name='freelancer_recipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField()),
                ('freelancer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='freelancer.Freelancer')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purposal_contract.Message')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(default=None, null=True)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.Company')),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freelancer.Freelancer')),
                ('payment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freelancer.Payment_type')),
                ('purposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purposal_contract.Purposal')),
            ],
        ),
        migrations.CreateModel(
            name='client_recipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField()),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.Hire_manager')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purposal_contract.Message')),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_link', models.FileField(upload_to='messages/')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purposal_contract.Message')),
            ],
        ),
    ]
