# Generated by Django 3.0.6 on 2020-09-29 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purposal_contract', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parent_message',
            old_name='parent_message',
            new_name='parent',
        ),
    ]
