# Generated by Django 3.0.6 on 2020-09-29 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_hire_manager_profile_pic'),
        ('freelancer', '0001_initial'),
        ('purposal_contract', '0002_auto_20200929_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freelancer.Freelancer')),
                ('hire_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.Hire_manager')),
            ],
        ),
        migrations.DeleteModel(
            name='Parent_message',
        ),
    ]
