# Generated by Django 3.0.6 on 2020-08-13 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='title',
            field=models.TextField(default=121),
            preserve_default=False,
        ),
    ]
