# Generated by Django 3.0.6 on 2020-08-21 17:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='published',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 8, 21, 17, 30, 52, 225666, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='payment_amount',
            field=models.IntegerField(max_length=100),
        ),
    ]
