# Generated by Django 3.0.6 on 2020-08-26 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0001_initial'),
        ('job', '0004_auto_20200826_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expected_duration',
            name='main_skill',
        ),
        migrations.RemoveField(
            model_name='job',
            name='other_skill',
        ),
        migrations.AddField(
            model_name='expected_duration',
            name='other_skill',
            field=models.ManyToManyField(to='freelancer.Skill'),
        ),
        migrations.AddField(
            model_name='job',
            name='main_skill',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, to='freelancer.Skill'),
            preserve_default=False,
        ),
    ]
