# Generated by Django 3.0.6 on 2020-08-26 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_auto_20200826_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='payment_amount',
            field=models.IntegerField(),
        ),
    ]
